export interface TarotCard {
  id: string
  name: string
  arcana: "major" | "minor"
  suit?: "cups" | "wands" | "swords" | "pentacles"
  number?: number
  uprightMeaning: string
  reversedMeaning: string
  keywords: string[]
  astrologicalCorrespondence: string
  element?: string
}

export const majorArcana: TarotCard[] = [
  {
    id: "fool",
    name: "The Fool",
    arcana: "major",
    number: 0,
    uprightMeaning: "New beginnings, innocence, spontaneity, free spirit, adventure",
    reversedMeaning: "Recklessness, taken advantage of, inconsideration, naivety",
    keywords: ["beginnings", "innocence", "spontaneity", "free spirit"],
    astrologicalCorrespondence: "Uranus",
    element: "Air",
  },
  {
    id: "magician",
    name: "The Magician",
    arcana: "major",
    number: 1,
    uprightMeaning: "Manifestation, resourcefulness, power, inspired action",
    reversedMeaning: "Manipulation, poor planning, untapped talents",
    keywords: ["manifestation", "power", "action", "resourcefulness"],
    astrologicalCorrespondence: "Mercury",
    element: "Air",
  },
  {
    id: "high-priestess",
    name: "The High Priestess",
    arcana: "major",
    number: 2,
    uprightMeaning: "Intuition, sacred knowledge, divine feminine, subconscious mind",
    reversedMeaning: "Secrets, disconnected from intuition, withdrawal",
    keywords: ["intuition", "mystery", "subconscious", "divine feminine"],
    astrologicalCorrespondence: "Moon",
    element: "Water",
  },
  {
    id: "empress",
    name: "The Empress",
    arcana: "major",
    number: 3,
    uprightMeaning: "Femininity, beauty, nature, nurturing, abundance",
    reversedMeaning: "Creative block, dependence on others, emptiness",
    keywords: ["abundance", "nurturing", "fertility", "nature"],
    astrologicalCorrespondence: "Venus",
    element: "Earth",
  },
  {
    id: "emperor",
    name: "The Emperor",
    arcana: "major",
    number: 4,
    uprightMeaning: "Authority, establishment, structure, father figure",
    reversedMeaning: "Domination, excessive control, lack of discipline",
    keywords: ["authority", "structure", "control", "father figure"],
    astrologicalCorrespondence: "Aries",
    element: "Fire",
  },
  {
    id: "hierophant",
    name: "The Hierophant",
    arcana: "major",
    number: 5,
    uprightMeaning: "Spiritual wisdom, religious beliefs, conformity, tradition",
    reversedMeaning: "Personal beliefs, freedom, challenging the status quo",
    keywords: ["tradition", "conformity", "morality", "ethics"],
    astrologicalCorrespondence: "Taurus",
    element: "Earth",
  },
  {
    id: "lovers",
    name: "The Lovers",
    arcana: "major",
    number: 6,
    uprightMeaning: "Love, harmony, relationships, values alignment, choices",
    reversedMeaning: "Self-love, disharmony, imbalance, misalignment of values",
    keywords: ["love", "harmony", "relationships", "choices"],
    astrologicalCorrespondence: "Gemini",
    element: "Air",
  },
  {
    id: "chariot",
    name: "The Chariot",
    arcana: "major",
    number: 7,
    uprightMeaning: "Control, willpower, success, action, determination",
    reversedMeaning: "Self-discipline, opposition, lack of direction",
    keywords: ["control", "willpower", "victory", "determination"],
    astrologicalCorrespondence: "Cancer",
    element: "Water",
  },
  {
    id: "strength",
    name: "Strength",
    arcana: "major",
    number: 8,
    uprightMeaning: "Strength, courage, persuasion, influence, compassion",
    reversedMeaning: "Inner strength, self-doubt, low energy, raw emotion",
    keywords: ["strength", "courage", "patience", "control"],
    astrologicalCorrespondence: "Leo",
    element: "Fire",
  },
  {
    id: "hermit",
    name: "The Hermit",
    arcana: "major",
    number: 9,
    uprightMeaning: "Soul searching, introspection, being alone, inner guidance",
    reversedMeaning: "Isolation, loneliness, withdrawal",
    keywords: ["introspection", "solitude", "guidance", "wisdom"],
    astrologicalCorrespondence: "Virgo",
    element: "Earth",
  },
  {
    id: "wheel-of-fortune",
    name: "Wheel of Fortune",
    arcana: "major",
    number: 10,
    uprightMeaning: "Good luck, karma, life cycles, destiny, turning point",
    reversedMeaning: "Bad luck, resistance to change, breaking cycles",
    keywords: ["change", "cycles", "fate", "turning point"],
    astrologicalCorrespondence: "Jupiter",
    element: "Fire",
  },
  {
    id: "justice",
    name: "Justice",
    arcana: "major",
    number: 11,
    uprightMeaning: "Justice, fairness, truth, cause and effect, law",
    reversedMeaning: "Unfairness, lack of accountability, dishonesty",
    keywords: ["justice", "fairness", "truth", "law"],
    astrologicalCorrespondence: "Libra",
    element: "Air",
  },
  {
    id: "hanged-man",
    name: "The Hanged Man",
    arcana: "major",
    number: 12,
    uprightMeaning: "Pause, surrender, letting go, new perspectives",
    reversedMeaning: "Delays, resistance, stalling, indecision",
    keywords: ["surrender", "letting go", "pause", "new perspective"],
    astrologicalCorrespondence: "Neptune",
    element: "Water",
  },
  {
    id: "death",
    name: "Death",
    arcana: "major",
    number: 13,
    uprightMeaning: "Endings, change, transformation, transition",
    reversedMeaning: "Resistance to change, personal transformation, inner purging",
    keywords: ["transformation", "endings", "change", "transition"],
    astrologicalCorrespondence: "Scorpio",
    element: "Water",
  },
  {
    id: "temperance",
    name: "Temperance",
    arcana: "major",
    number: 14,
    uprightMeaning: "Balance, moderation, patience, purpose",
    reversedMeaning: "Imbalance, excess, self-healing, re-alignment",
    keywords: ["balance", "moderation", "patience", "purpose"],
    astrologicalCorrespondence: "Sagittarius",
    element: "Fire",
  },
  {
    id: "devil",
    name: "The Devil",
    arcana: "major",
    number: 15,
    uprightMeaning: "Shadow self, attachment, addiction, restriction, sexuality",
    reversedMeaning: "Releasing limiting beliefs, exploring dark thoughts, detachment",
    keywords: ["bondage", "addiction", "sexuality", "materialism"],
    astrologicalCorrespondence: "Capricorn",
    element: "Earth",
  },
  {
    id: "tower",
    name: "The Tower",
    arcana: "major",
    number: 16,
    uprightMeaning: "Sudden change, upheaval, chaos, revelation, awakening",
    reversedMeaning: "Personal transformation, fear of change, averting disaster",
    keywords: ["upheaval", "chaos", "sudden change", "revelation"],
    astrologicalCorrespondence: "Mars",
    element: "Fire",
  },
  {
    id: "star",
    name: "The Star",
    arcana: "major",
    number: 17,
    uprightMeaning: "Hope, faith, purpose, renewal, spirituality",
    reversedMeaning: "Lack of faith, despair, self-trust, disconnection",
    keywords: ["hope", "faith", "renewal", "inspiration"],
    astrologicalCorrespondence: "Aquarius",
    element: "Air",
  },
  {
    id: "moon",
    name: "The Moon",
    arcana: "major",
    number: 18,
    uprightMeaning: "Illusion, fear, anxiety, subconscious, intuition",
    reversedMeaning: "Release of fear, repressed emotion, inner confusion",
    keywords: ["illusion", "intuition", "dreams", "subconscious"],
    astrologicalCorrespondence: "Pisces",
    element: "Water",
  },
  {
    id: "sun",
    name: "The Sun",
    arcana: "major",
    number: 19,
    uprightMeaning: "Positivity, fun, warmth, success, vitality",
    reversedMeaning: "Inner child, feeling down, overly optimistic",
    keywords: ["success", "vitality", "joy", "confidence"],
    astrologicalCorrespondence: "Sun",
    element: "Fire",
  },
  {
    id: "judgement",
    name: "Judgement",
    arcana: "major",
    number: 20,
    uprightMeaning: "Judgement, rebirth, inner calling, absolution",
    reversedMeaning: "Self-doubt, inner critic, ignoring the call",
    keywords: ["judgement", "rebirth", "inner calling", "absolution"],
    astrologicalCorrespondence: "Pluto",
    element: "Fire",
  },
  {
    id: "world",
    name: "The World",
    arcana: "major",
    number: 21,
    uprightMeaning: "Completion, integration, accomplishment, travel",
    reversedMeaning: "Seeking personal closure, short-cuts, delays",
    keywords: ["completion", "accomplishment", "travel", "fulfillment"],
    astrologicalCorrespondence: "Saturn",
    element: "Earth",
  },
]

export function getRandomCards(count: number): TarotCard[] {
  const shuffled = [...majorArcana].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}

export function getCardById(id: string): TarotCard | undefined {
  return majorArcana.find((card) => card.id === id)
}
